apiVersion: apps/v1
kind: Deployment
metadata:
  name: daisyui-dashboard
  namespace: dashboard-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daisyui-dashboard
  template:
    metadata:
      labels:
        app: daisyui-dashboard
    spec:
      containers:
      - name: dashboard
        image: shubhamj2024/daisyui-dashboard:latest
        ports:
        - containerPort: 3000
