apiVersion: v1
kind: Service
metadata:
  name: daisyui-dashboard-service
spec:
  type: NodePort
  selector:
    app: daisyui-dashboard
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
