pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'shubhamj2024/daisyui-dashboardv1:latest'
    }

    stages {
        stage('Pull Docker Image') {
            steps {
                sh "docker pull $DOCKER_IMAGE"
            }
        }

        stage('Docker Compose Restart') {
            steps {
                sh '''
                    docker-compose down
                    docker-compose up --build -d
                '''
            }
        }
    }
}
